baseURL: https://jacksprojects.netlify.app
title: Rxive
theme: hugo-theme-m10c
paginate: 5
menu:
  main:
    - identifier: home
      name: Home
      url: /
    - identifier: tags
      name: Tags
      url: /tags/
params:
  author: Jack Quarm
  description: Data and Webdev blog about about various topics R, Python, Web and Linux.
  menu_item_separator: ' - '
  social:
    - name: github
      url: https://github.com/gohugoio
    - name: linkedin
      url: https://www.linkedin.com/in/jack-quarm-987b31158/
